### ISSUE TITLE
History prior to 1972?

### ISSUE THREAD

**Issue by dmcclean** [bjornbm/leapseconds-announced#1]
Can you comment on the origin of the difference between this package and the list of leap seconds [in the Wikipedia article](http://en.wikipedia.org/wiki/Leap_second) and in [the machine-readable file published by NIST](ftp://time.nist.gov/pub/leap-seconds.list), both of which begin with the 1/1/72 leap second?

I ask because I was making an attoparsec parser for the latter, to provide updates to this information without (a) recompiling or (b) needing to see at least one GPS navigation message every six months.

**Comment by bjornbm** [comment]
My source is the DAT column of the file http://www.celestrak.com/SpaceData/eop19620101.txt. Documentation for the file at http://celestrak.com/SpaceData/. The reason I use this file is that I happened to have a parser for it as I am interested in the other data in the file too.

Regarding the leap seconds prior to 1972-01-01: I haven't worried too much (or thought too hard) about them as they aren't really relevant to me. I'm not sure how they were determined in the file and what is specified as the source (http://maia.usno.navy.mil/ser7/tai-utc.dat) is giving me a "Recv failure: Connection reset by peer" right now. I expect DAT prior to 1972 is a hypothetical leap second for a SI second UTC prior to 1972. But one should probably be very careful in how one uses this information and in retrospect it probably does not make sense to include them here.

Side note: my leap seconds prior to 1972 are for some reason that eludes me incomplete. Rerunning my parser gives the full table: 

```
leapSeconds :: [(Day, Integer)]
leapSeconds = (fromGregorian 2015 07 01, 36)
  : (fromGregorian 2012 07 01, 35)
  : (fromGregorian 2009 01 01, 34)
  : (fromGregorian 2006 01 01, 33)
  : (fromGregorian 1999 01 01, 32)
  : (fromGregorian 1997 07 01, 31)
  : (fromGregorian 1996 01 01, 30)
  : (fromGregorian 1994 07 01, 29)
  : (fromGregorian 1993 07 01, 28)
  : (fromGregorian 1992 07 01, 27)
  : (fromGregorian 1991 01 01, 26)
  : (fromGregorian 1990 01 01, 25)
  : (fromGregorian 1988 01 01, 24)
  : (fromGregorian 1985 07 01, 23)
  : (fromGregorian 1983 07 01, 22)
  : (fromGregorian 1982 07 01, 21)
  : (fromGregorian 1981 07 01, 20)
  : (fromGregorian 1980 01 01, 19)
  : (fromGregorian 1979 01 01, 18)
  : (fromGregorian 1978 01 01, 17)
  : (fromGregorian 1977 01 01, 16)
  : (fromGregorian 1976 01 01, 15)
  : (fromGregorian 1975 01 01, 14)
  : (fromGregorian 1974 01 01, 13)
  : (fromGregorian 1973 01 01, 12)
  : (fromGregorian 1972 07 01, 11)
  : (fromGregorian 1971 08 03, 10)
  : (fromGregorian 1970 07 13, 9)
  : (fromGregorian 1969 06 23, 8)
  : (fromGregorian 1968 06 02, 7)
  : (fromGregorian 1967 04 04, 6)
  : (fromGregorian 1966 03 15, 5)
  : (fromGregorian 1965 01 01, 4)
  : (fromGregorian 1963 08 07, 3)
  : (fromGregorian 1962 01 01, 2)
  : []
```

**Comment by dmcclean** [comment]
Awesome, thanks for the research. I will proceed with parsing the other file and using that table directly, since whatever happened before 2015 is of no concern to my application and it doesn't appear to be symptomatic of a larger disagreement that could come up again in the future.
