### ISSUE TITLE
Consider uploading to Stackage

### ISSUE THREAD

**Issue by ruuda** [bjornbm/leapseconds-announced#4]
This package is not on [Stackage](https://www.stackage.org/), so projects that build with `stack` cannot use it as a dependency. Please consider updating [stackage/build-constraints.yaml](https://github.com/fpco/stackage/blob/master/build-constraints.yaml) to include this package.

**Comment by bjornbm** [comment]
Pull request made to [stackage/build-constraints.yaml](https://github.com/fpco/stackage/blob/master/build-constraints.yaml).

**Comment by ruuda** [comment]
Great, thanks!

**Comment by bjornbm** [comment]
Closed with the merge of https://github.com/fpco/stackage/pull/1701
